# Generated by Django 5.1.4 on 2024-12-28 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CulinaryUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Herb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='herb_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinalUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrowingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=255, null=True)),
                ('watering_needs', models.CharField(blank=True, max_length=255, null=True)),
                ('temperature', models.CharField(blank=True, max_length=255, null=True)),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.herb')),
            ],
        ),
        migrations.CreateModel(
            name='HerbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.category')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.herb')),
            ],
            options={
                'unique_together': {('herb', 'category')},
            },
        ),
        migrations.CreateModel(
            name='HerbCulinaryUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culinary_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.culinaryuse')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.herb')),
            ],
            options={
                'unique_together': {('herb', 'culinary_use')},
            },
        ),
        migrations.CreateModel(
            name='HerbMedicinalUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.herb')),
                ('medicinal_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.medicinaluse')),
            ],
            options={
                'unique_together': {('herb', 'medicinal_use')},
            },
        ),
        migrations.CreateModel(
            name='HerbRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.herb')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herbs.region')),
            ],
            options={
                'unique_together': {('herb', 'region')},
            },
        ),
    ]
