# Generated by Django 5.1.4 on 2024-12-31 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0002_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
