# Generated by Django 5.1.4 on 2024-12-29 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0002_remove_herb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbmedicinaluse',
            name='herb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herbmedicinaluses', to='herbs.herb'),
        ),
        migrations.AlterField(
            model_name='herbmedicinaluse',
            name='medicinal_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herbmedicinaluses', to='herbs.medicinaluse'),
        ),
    ]
