# Generated by Django 5.1.4 on 2024-12-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0003_delete_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='herb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='herbs/'),
        ),
        migrations.AddField(
            model_name='herb',
            name='unsplash_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
