# Generated by Django 5.1.4 on 2024-12-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0004_herb_image_herb_unsplash_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herb',
            name='unsplash_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
