# Generated by Django 5.1.4 on 2024-12-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herbs', '0006_herb_medicinal_uses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herb',
            name='medicinal_uses',
        ),
    ]
